#服务配置
server:
  port: 9002

#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #3.配置jpa
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

  redis:
    host: 127.0.0.1
    port: 6379

  output:
    ansi:
      enabled: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #设置为东八区时间
    time-zone: GMT+8


jwt:
  config:
    key: saas-ihrm
    ttl: 3600000

